/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package taskquest.app

import com.dustinredmond.fxtrayicon.FXTrayIcon
import javafx.application.Application
import javafx.stage.Stage
import taskquest.app.javafx.*
class App: Application() {
    override fun start(stage: Stage?) {
        val display = MainBoardDisplay()
        display.start_display(stage)
    }
}

fun main() {
    Application.launch(App::class.java)
}
